# Generated by Django 2.2.6 on 2019-10-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapi', '0005_auto_20191027_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Paid'), ('D', 'Delivered')], max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.UserProfile')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTPBackend.Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTPBackend.Item')),
            ],
        ),
    ]
