# Generated by Django 2.2.6 on 2019-10-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTPBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
    ]
