# Generated by Django 2.2.6 on 2019-11-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RTPBackend', '0002_remove_order_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_to_pay', to='userapi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_to_check', to='userapi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='RTPBackend.Invoice'),
        ),
    ]
