# Generated by Django 2.2.6 on 2019-10-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTPBackend', '0002_remove_order_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
