# Generated by Django 2.2.6 on 2019-11-23 20:18

import RTPBackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTPBackend', '0003_auto_20191123_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=RTPBackend.models.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
