# Generated by Django 2.2.6 on 2019-10-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RTPBackend', '0003_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='RTPBackend.Invoice'),
        ),
    ]
