# Generated by Django 2.2.6 on 2019-11-25 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RTPBackend', '0004_auto_20191123_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_to_pay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_to_check', to=settings.AUTH_USER_MODEL),
        ),
    ]
