# Generated by Django 2.2.6 on 2019-10-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('user_type', models.CharField(choices=[('S', 'Suppliers'), ('C', 'Customer'), ('D', 'Driver')], max_length=1)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
