# Generated by Django 2.2.6 on 2019-10-27 04:17

from django.db import migrations
import userapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userapi.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
