# Generated by Django 2.2.6 on 2019-10-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0005_auto_20191027_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='is_delivering',
        ),
    ]
