# Generated by Django 2.2.6 on 2019-10-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0006_auto_20191028_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_delivering',
        ),
    ]
