# Generated by Django 2.2.6 on 2019-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0007_remove_userprofile_is_delivering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('S', 'Supplier'), ('C', 'Customer'), ('D', 'Driver')], max_length=1),
        ),
    ]
