# Generated by Django 2.2.7 on 2019-11-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0009_user_email_verified'),
        ('userapi', '0008_auto_20191121_1529'),
    ]

    operations = [
    ]
