# Generated by Django 2.2.6 on 2019-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTPBackend', '0005_auto_20191124_2106'),
        ('userapi', '0010_merge_20191124_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Supplier'), ('C', 'Customer'), ('D', 'Driver')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
