# Generated by Django 2.2.7 on 2019-11-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0010_merge_20191124_1720'),
        ('userapi', '0010_merge_20191124_1409'),
    ]

    operations = [
    ]
